spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
    user: postgres
    password: postgres
    locations: classpath:db/migration


server:
  port: 8050