version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e-commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - microservices-net
    restart: unless-stopped
    depends_on:
      - postgres-db

  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_express_container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb  # Ensure this matches MongoDB service name
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: always
    depends_on:
      - mongodb

  maildev:
    image: maildev/maildev:2.1.0
    container_name: maildev_container
    ports:
      - "1080:80"
      - "1025:25"
    networks:
      - microservices-net
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data:

networks:
  microservices-net:
    driver: bridge
